# commits should be a list of strings.
# defaultCommitsListURL should be a URL pointing to a plain text file with one commit message per line.
# these will be appended to commits.
commits:
  - "Hello, World!"
defaultCommitListURL: "https://raw.githubusercontent.com/ngerakines/commitment/master/commit_messages.txt"